# -*- coding: utf-8 -*-
"""despliegue_adult.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIaPu0ILGwPq-ZkTuXnYMJ-6jfMHifif
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pickle
filename = 'modelo-class.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

#df = pd.read_csv("/content/adult_futuros.csv")
#df.head()

#gui
import streamlit as st

st.title('Predicción salario > 50k')
age = st.slider('Age', min_value = 17, max_value = 100, step = 1, value = 20)
workclass = st.selectbox('Workclass', ["'Private'", "' Self-emp-not-inc'", "' Local-gov'", "' State-gov'", "' Self-emp-inc'", "' Federal-gov'", "' Without-pay'", "' Never-worked'"])
education = st.selectbox('Education', ["' Bachelors'","' HS-grad'","' 11th'","' Masters'","' 9th'","' Some-college'","' Assoc-acdm'","' Assoc-voc'","' 7th-8th'","' Doctorate'","' Prof-school'","' 5th-6th'","' 10th'","' 1st-4th'","' Preschool'","' 12th'"])
marital_status = st.selectbox('Marital status', ["' Married-civ-spouse'","' Divorced'","' Married-spouse-absent'","' Never-married'","' Separated'","' Married-AF-spouse'","' Widowed'"])
occupation = st.selectbox('Occupation',["' Exec-managerial'","' Handlers-cleaners'","' Prof-specialty'","' Other-service'","' Adm-clerical'","' Sales'","' Craft-repair'","' Transport-moving'","' Farming-fishing'","' Machine-op-inspct'","' Tech-support'","' Protective-serv'","' Armed-Forces'","' Priv-house-serv'"])
sex = st.selectbox('Sex', ["' Male'","' Female'"])
capital_gain = st.number_input("Ingrese el capital gain")
capital_loss = st.number_input("Ingrese el capital loss")
hours = st.number_input("Ingrese la cantidad de horas laboradas")
datos = [[age, workclass, education, marital_status, occupation, sex, capital_gain, capital_loss, hours]]
df = pd.DataFrame(datos, columns = ['age', 'workclass','education', 'marital-status', 'occupation',
                                          'sex', 'capital-gain', 'capital-loss', 'hours-per-week'])

data_preparada = df.copy()

data_preparada = pd.get_dummies(data = data_preparada, drop_first=False,
                                columns =['workclass','education', 'marital-status', 'occupation',
                                          'sex'], dtype = int)
data_preparada.head()

data_preparada = data_preparada.reindex(columns=variables, fill_value=0)
data_preparada.head()

"""PREDICCIONES"""

clases = {0:'<=50K',
          1:'>50K'}
y_pred = modelo.predict(data_preparada)
resultado = clases[y_pred[0]]
print(y_pred)

df['prediccion'] = resultado
df.head()

df

st.warning("El modelo tiene un error del 14%")